---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: focal
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ""
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: true
  - name: jammy
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: true
  - name: noble
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    command: ""
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
